// PRIESTATE — Railway infrastructure-as-code (backend).
//
// Server-side deployment only. Derived secrets (OTP/account/biometric keys)
// are generated by Railway via ctx.randomString and never appear in this
// repo. Real provider credentials (SMTP user/pass, Google/SMS/WhatsApp/Aadhaar
// tokens) are referenced from shared network variables and left EMPTY until
// a real credential is entered in the Railway UI — they are never invented.

import { define, github, preserve, project, service, volume } from "railway/iac";

export default define((ctx) => {
  const dataVolume = volume("data", {
    sizeMB: 500,
    region: "iad",
  });

  const backend = service("backend", {
    source: github("techwithjainparam/midnight-moonshot", {
      branch: "main",
    }),
    build: {
      // Railway installs dependencies then runs buildCommand. Mirror the
      // pinned compact-toolchain install that CI uses so contracts compile.
      buildCommand:
        "export PATH=\"$HOME/.local/bin:$HOME/.compact/bin:$PATH\"; if ! command -v compact >/dev/null 2>&1; then curl -LsSf -o /tmp/compact-installer.sh https://github.com/midnightntwrk/compact/releases/download/compact-v0.5.1/compact-installer.sh && sh /tmp/compact-installer.sh; fi && compact update 0.31.1 && npm run build",
    },
    deploy: {
      startCommand: "npm run verify-server",
      numReplicas: 1,
    },
    networking: {
      // Railway-generated public HTTPS service domain (*.up.railway.app).
      serviceDomains: { "": {} },
    },
    volumeMounts: {
      "/data": dataVolume,
    },
    env: {
      NODE_ENV: "production",
      NODE_VERSION: "22.x",
      ACCOUNT_DB_PATH: "/data/priestate-accounts.db",
      VERIFY_SERVER_ALLOWED_ORIGIN: "https://priestate.vercel.app",
      VERIFY_SERVER_TRUST_PROXY: "true",
      ACCOUNT_SESSION_SECURE: "true",
      ACCOUNT_SESSION_SAMESITE: "None",
      // Railway-derived secrets (never committed).
      OTP_HASH_SECRET: ctx.randomString("otp-hash", 32),
      ACCOUNT_ENC_SECRET: ctx.randomString("account-enc", 32),
      ACCOUNT_BIOMETRIC_ENC_SECRET: ctx.randomString("account-bioenc", 32),
      // Real SMTP credentials live in the Railway dashboard and are never
      // invented; preserve() keeps anything entered there without clobbering.
      SMTP_HOST: preserve(),
      SMTP_PORT: preserve(),
      SMTP_USER: preserve(),
      SMTP_PASS: preserve(),
      SMTP_SECURE: preserve(),
      EMAIL_FROM: preserve(),
    },
  });

  return project("priestate-backend", {
    resources: [backend, dataVolume],
  });
});