// PRIESTATE — OAuth2 state/nonce challenge store (server-side only).
//
// ⚠️ SERVER-SIDE ONLY. Never bundled into the browser.
//
// Holds per-`state` OAuth challenges for the Google authorization-code flow.
// Each challenge is:
//   * cryptographically random (generated by the callers with randomBytes),
//   * bound to the initiating wallet,
//   * short-lived (TTL, swept periodically),
//   * single-use (consumed on completion so it cannot be replayed),
//   * holding a server-kept `nonce` that must be echoed back by the in-app
//     client on completion and compared to the ID-token `nonce` claim.
//
// Nothing here is persisted to disk or the ledger; the store is in-memory so a
// leaked database can never expose secrets, and tokens/codes are never logged.

export interface OAuthChallenge {
  readonly wallet: string;
  readonly state: string;
  readonly nonce: string;
  readonly codeVerifier?: string;
  readonly createdAt: number;
  readonly expiresAt: number;
  /**
   * Set true only after the server successfully verified an OAuth2
   * authorization redirect (code exchange + ID-token/userinfo validation)
   * for this state. A challenge that never survived a server-verified
   * redirect can never be completed — auth is never fabricated.
   */
  redirectVerified: boolean;
  consumed: boolean;
}

export interface OauthStateSessionOptions {
  readonly now?: () => number;
  readonly ttlMs?: number;
}

export class OAuthStateSession {
  private readonly challenges = new Map<string, OAuthChallenge>();
  private readonly now: () => number;
  readonly ttlMs: number;

  constructor(options: OauthStateSessionOptions = {}) {
    this.now = options.now ?? Date.now;
    this.ttlMs = options.ttlMs ?? 10 * 60 * 1000;
  }

  issue(challenge: {
    wallet: string;
    state: string;
    nonce: string;
    codeVerifier?: string;
  }): void {
    const t = this.now();
    this.challenges.set(challenge.state, {
      wallet: challenge.wallet,
      state: challenge.state,
      nonce: challenge.nonce,
      codeVerifier: challenge.codeVerifier,
      createdAt: t,
      expiresAt: t + this.ttlMs,
      redirectVerified: false,
      consumed: false,
    });
  }

  /** Look up a live (non-expired, non-consumed) challenge. */
  peek(state: string): OAuthChallenge | null {
    const c = this.challenges.get(state);
    if (!c) return null;
    if (c.consumed) return null;
    if (this.now() >= c.expiresAt) {
      this.challenges.delete(state);
      return null;
    }
    return c;
  }

  /** Non-destructive raw lookup (used to distinguish `expired` in callers). */
  get(state: string): OAuthChallenge | null {
    return this.challenges.get(state) ?? null;
  }

  /** Consume (invalidate) a challenge. Used for login (server-held nonce). */
  consume(state: string): OAuthChallenge | null {
    const c = this.challenges.get(state);
    if (!c) return null;
    c.consumed = true;
    this.challenges.delete(state);
    return c;
  }

  /** Remove all expired challenges; called periodically by the sweep loop. */
  sweep(): void {
    const t = this.now();
    for (const [state, c] of this.challenges) {
      if (t >= c.expiresAt) this.challenges.delete(state);
    }
  }

  clear(): void {
    this.challenges.clear();
  }
}
